default:
  image: python:3.8
  before_script:
    - apt-get update && apt install libgl1-mesa-glx -y
    - python -m pip install -r requirements.txt

pytest:
  stage: test
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
    - python -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 2 days
