default:
  image: python:3.8
  before_script:
    - python -m pip install -r requirements.txt

pytest:
  stage: test
  script:
    - python -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 2 days
